Implement sorting of events via config file
Uninett/Howitz pull request #81
Opened 2024-03-13 09:34 UTC by podliashanyk

Related discussion #96

Depends on https://github.com/Uninett/zinolib/pull/61

### Implemented changes:

- [x] Added all sorting methods that exist in Ritz TK
- [x] Added a default sorting (the unchanged order in which server sends events)
- [x] Added a definition for a default sorting used in curitz and by SSC (called _lasttrans_)
- [x] Sorting method can only be changed via config file
- [x] Document configurable sorting methods
- [x] Made NTIE work with sorting (using `SimpleCache` from flask-caching)

### Attention needed:

- to the implementation itself. Are there redundancies, smelly code etc?
- should sorting methods definitions and methods be moved somewhere else from `endpoints.py`?
- I have tested whether order of events matches with the ones in Ritz TK/Curitz. The original sorting methods in TK are not documented, so I had to reverse engineer them and guess what set of parameters each sorting method goes after. So a test by another person would be nice.
- do you have better names? I have followed the original naming for methods so far.

### Further work:

- ~Make it possible to change sorting method via web UI~ (not a part of original implementation in Curitz)

2024-03-15 10:03 UTC, hmpf requested changes

2024-03-15 10:03 UTC, hmpf commented on src/howitz/endpoints.py
> +class EventSorting(Enum):
Not quite happy with the name of this enum. `EventSort`? `EventSortKey`? `EventSortConfig`?

2024-03-21 09:31 UTC, stveit commented on src/howitz/endpoints.py
> +        obj._value_ = args[0]
`_value_` seems to be where Enums save the value or something

2024-03-21 09:31 UTC, stveit commented on src/howitz/endpoints.py
> +        return self._reversed_
yap seems like it is indeed magic for Enums

2024-06-06 10:59 UTC, hmpf reviewed
Will rereview after rebase.

NTS: tests, the big if

2024-06-12 10:47 UTC, hmpf requested changes

2024-06-12 10:47 UTC, hmpf commented on src/howitz/config/models.py
EventSort should not be in howitz.endpoints.

2024-06-12 10:47 UTC, hmpf commented on src/howitz/config/models.py
EventColor shouldn't be there either. Hm, where to put them.

2024-06-12 10:47 UTC, hmpf commented on src/howitz/endpoints.py
> +    events_sorted = sort_events(events, sort_by=EventSort(session["sort_by"]))
Good, independently testable sort.

2024-06-12 10:47 UTC, hmpf commented on src/howitz/endpoints.py
> +                         reversed(
`if`, not `elif` here.

2024-06-12 10:47 UTC, hmpf commented on src/howitz/endpoints.py
> +                         }
Better if each `sorted(something)` is a testable function.

2024-06-12 10:47 UTC, hmpf commented on src/howitz/endpoints.py
> +                         }
If each if is its own function we could use a function map.

```
funcmap = {EventSort.SEVERITY: sort_on_severity, ..}
return funcmap.get(sort_by, fallback)(event_dict)
```

2024-06-12 10:47 UTC, hmpf commented on src/howitz/endpoints.py
> +        return 3
I would order these after priority, so the one that returns 4 first.

2024-06-12 10:47 UTC, hmpf commented on README.rst
> +* *lasttrans* - Newest transaction first, all IGNORED at the bottom. Default sorting in curitz.
Maybe `default` should be named `unsorted` or `raw` instead.

2024-06-12 11:01 UTC, hmpf commented on src/howitz/__init__.py
> +    cache.init_app(app)
Cache-type should be configurable.

2024-06-12 12:44 UTC, hmpf commented on howitz.toml.example
> +
Maybe these should live under `flask`.

2024-06-12 12:52 UTC, hmpf commented on howitz.toml.example
> +
What I mean is: I suspect we don't need to parse these but that they can be picked from the environment in the same way as flask's own config vars.

2024-06-12 13:20 UTC, merged