Add clear flapping functionality
Uninett/Howitz pull request #85
Opened 2024-03-18 14:28 UTC by podliashanyk

Closes #66 

### Implemented changes:

- Selected events are now stored as dict in session in order to keep info about type of selected events. This is because clear flapping functionality is only applicable to `portstate` events. Therefore clear flapping button in bulk menu is shown only if all selected events are of type `portstate`.
- Enabled clear flapping button in detailed event view for `portstate` events.
- Removed clear flapping button from detailed event view for events that are not `portstate`.

2024-04-04 11:57 UTC, hmpf requested changes

2024-04-04 11:57 UTC, hmpf commented on src/howitz/endpoints.py
> +        session["selected_events"][str(i)] = event_type
What happens if event_type is the empty string?

2024-04-04 11:57 UTC, hmpf commented on src/howitz/endpoints.py
> +        session["selected_events"][str(i)] = event_type
And "i" is a bit short. Is it an event_id? Call it "event_id". Is it the numerical index in a list? Call it "index".

Also, which line raises the expected ValueError?

2024-04-04 11:57 UTC, hmpf commented on src/howitz/endpoints.py
> +    show_clear_flapping = all(event == 'portstate' for event in session.get("selected_events", dict(k='v')).values())
Break up the line, this is really hard to read. First handle empty `session["selected_events"]`.

2024-05-22 06:28 UTC, hmpf requested changes

2024-05-22 06:28 UTC, hmpf commented on src/howitz/endpoints.py
> +
Route: '/event/<int:event_id>/clear-flapping'

.. then you can get rid of the `event_id = int(i)` line.

2024-05-22 06:28 UTC, hmpf commented on src/howitz/endpoints.py
> +    session.modified = True
`event_id` from the route is `str` by defualt so you shouldn't need to cast.

2024-06-06 10:52 UTC, hmpf approved these changes

2024-06-06 11:10 UTC, lunkwill42 approved these changes
Looks ok to me.  Works as long as I merge with main first...

2024-06-07 11:46 UTC, merged